# This file was generated by GoReleaser. DO NOT EDIT.
cask "scoutly@beta" do
  version "0.5.0-beta.1"

  on_macos do
    on_arm do
      sha256 "f9bfd9588f07a7b316965dc0f36cbdef4ca29afd701f617359541c6dee5c7f1f"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5690b489786edc9545c5d3e9a2179a1555167f98bef5e2395fe6470335a03ea0"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3bee4b171b0e567af7507bb3f860307a82d385352ed4c9bbcf1cb299c1cce931"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "02ee57c53d6f125ec8df49d1d9ca89602798c09f73044bd49c1f7d9a283b2b5c"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Linux_x86_64.tar.gz"
    end
  end

  name "scoutly@beta"
  desc "Fast website auditing tool"
  homepage "https://github.com/nelsonlaidev/scoutly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scoutly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/scoutly"]
    end
  end

  # No zap stanza required
end
