# This file was generated by GoReleaser. DO NOT EDIT.
cask "scoutly" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "84dd240c94991c5051198b45bf1706e51e7bcf5c6e7b6229ad6f4988c336e48c"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "619d731614e1f1033c123ddbc59707fc0f283f264bd062bb7869738d5d2495c9"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a6cf942bd2a6c7659c5ed79db7e36802e85b7675cfc1dab7396b1d1d6565d7ab"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1effb1ccdee97f2511755cf93f82ab1a017b2af592582c48bf5de027b642dd1f"
      url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly_Linux_x86_64.tar.gz"
    end
  end

  name "scoutly"
  desc "Fast website auditing tool"
  homepage "https://github.com/nelsonlaidev/scoutly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scoutly"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/scoutly"]
    end
  end

  # No zap stanza required
end
