# This file is generated by Scoutly release automation. DO NOT EDIT.
cask "scoutly@beta" do
  arch arm: "aarch64", intel: "x86_64"
  os macos: "apple-darwin", linux: "unknown-linux-gnu"

  version "0.6.0-beta.1"
  sha256 arm:          "2c26d22100d1280565ed837eb3ce74b5e18158be96f9c72b4a008da300a3d44d",
         intel:        "ff244a41aa65d26247359af21381a3e4b5fa32d6d69d7445174282ba4f537522",
         arm64_linux:  "21323942640810d0929cb9b1b482ba6b327869435af1ba6cb1e7815a79d40d29",
         x86_64_linux: "2e679948caa8ce858ddcfb8b59b57a37891aa3c0846116fd48495fadb514569a"

  url "https://github.com/nelsonlaidev/scoutly/releases/download/v#{version}/scoutly-#{arch}-#{os}.tar.xz"
  name "Scoutly Beta"
  desc "Fast website auditing tool"
  homepage "https://github.com/nelsonlaidev/scoutly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scoutly-#{arch}-#{os}/scoutly", target: "scoutly"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/scoutly-{{arch}}-apple-darwin/scoutly"]
    end
  end
end
